### ISSUE TITLE
Update of starter-template branch?

### ISSUE THREAD

**Issue by autolyticus** [ehllie/dotfiles#2]
Hi! 

I have been getting started with my long-put off revamp of my dotfiles, I want to integrate the latest generation of command line tools and I came across your dotfiles repository via https://flake.parts/options/ez-configs 

This repo seems great and checks all the boxes. It's clear that a lot of effort and love was put into this repository and I love it!

I think I understand broadly the interface that `ez-configs` provides and provides a much more ergonomic alternative to my hackish import code.

I think I figured it out but I found it hard to immediately understand step-by-step what I would need to do to set up a brand new system from scratch. By this I don't mean seeing how to access the various attrs provided, but how to set up and install a dotfiles repo.

Specifically, there doesn't seem to be any clear documentation on ezconfigs on what exactly I should be putting in my files under the various subdirectories.

I've had to go back and forth between the dotfiles repo and the ezconfigs repo to try to understand and I feel that this part could be much more simplified if you could simplify your current dotfiles and upgrade the `starter-template` branch to your latest best practices of dealing with stuff with some basic examples.

For eg. how to set `home.file` and `home.programs`, for home-manager and other simple tasks that a user might want to configure for darwin and nixos as well.

Also, I'm not sure if the instructions for how to use the dotfiles repo have changed after the migration to ezconfigs. For instance, it's not immediately obvious how to do home-manager switch under the new system.

Perhaps the documentation from https://github.com/ehllie/dotfiles/tree/starter-template needs to be migrated to the https://github.com/ehllie/ez-configs repo as well

(EDIT: Just realised that you do have a `test-flake` in ezconfigs which would have saved me a lot of time if I had taken a look at first 🥲)

**Comment by ehllie** [comment]
Hi, thanks for using `ez-configs`! I'm happy it's useful to someone. I definitely want to clean up the nix modules in this repository, and have taken some steps towards that in the most recent commits. I've made the `starter-template` branch to help introduce a friend to nix, and haven't really touched it after that. I've started writing a blog post explaining `ez-configs` a while back, but ran out of motivation halfway through.

Getting things documented better is definitely a goal of mnie, but I think the `starter-template` is best kept within the `ez-configs` repository. It's mentioned in the readme that you can run `nix flake new --template github:ehllie/ez-configs` to setup a new flake repository using a template from it. I should however update the readme in here to no longer direct people to the `starter-template` branch.
